name: comcat
channels:
- conda-forge
- defaults
dependencies:
- ipython
- impactutils
- jupyter
- numpy
- obspy
- pandas
- pytest
- pytest-cov
- pytest-mpl
- python>=3.6
- xlrd
- xlwt
- openpyxl
- xlsxwriter

